### ISSUE TITLE
Viper control bug

### ISSUE THREAD

**Issue by joshburns717** [JPLRepo/Endurance#1]
When changing ships, or reverting a flight to the launchpad, the controls on the viper switch to a vertical configuration. I don't know how to fix it (I've messed around in the configs a bit), and it has followed me through two saves, with two different versions of the mod. I've transferred no files (Did a clean install of the mod for each save and version).
![screenshot4](https://cloud.githubusercontent.com/assets/17950060/13899328/e6491a06-edc1-11e5-97bd-e9f9ced2a796.png)
:

**Comment by JPLRepo** [comment]
I can't reproduce it. Can you give some more details of how and what leads up to this? So you launch a viper on its own or part of a larger vessel? Can you reproduce it without fail following a set of steps? In a new save file?

**Comment by JPLRepo** [comment]
Closing due to no response.
