### ISSUE TITLE
Crew Stuck in MB-75 Deployable Habitation Unit

### ISSUE THREAD

**Issue by 9Gotji** [JPLRepo/Endurance#19]
**KSP:** 1.3.1.1891 Windows 64bit

**Problem:** Crew can board to the  MB-75 Deployable Habitation Unit but can't get out. (No portrait on the right-bottom corner, no crew transfer option and no IVA view.)

**Mods installed:**
Endurance (from Interstellar) Continued... V1.6
Module Manager 2.8.1

**Reproduction steps:**
- Build a simply base with MB-75 and a pod like lander can (for crew spawning purpose).
- Assign a crew to a pod.
- EVA the crew and board the MB-75.
- Try to get the crew out.

**Log:**
[output_log.txt](https://drive.google.com/open?id=1ZTMzRlfQHNWK-Z2SucZ6sW7ImrZRKwmK)

**Screenshot:**
[Reproduction on the Launchpad](https://i.imgur.com/kFY9eS8.jpg)

**P.S.:** This problem is not occur with the MB-50 Mobile Analysis Unit 

Please advise me.

Thank you very much.

**Comment by 9Gotji** [comment]
I just tried to fix the issue by adding the `INTERNAL { name = MK3_CrewCab_Int }` and changing the `crewCapacityDeployed` to 16 (to match the internal configuration).

But I just find out that even if I have a EVA option, there's still a problem. 

**Problem:** Can't EVA due to "Hatches is obstructed can't exit"

**Screenshot:**
[Hatch is obstructed](https://i.imgur.com/pJsqJu6.jpg)

Thank you very much.

**Comment by JPLRepo** [comment]
This was fixed
